[package]
name = "floki"
version = "0.1.0"
authors = ["arthurprs <arthurprs@gmail.com>"]

[dependencies]
rustc-serialize = "*"
log = "*"
env_logger = "*"
mio = "0.4.*"
nix = "0.3.6"
toml = "*"
threadpool = "*"
time = "*"
num_cpus = "*"
fnv = "*"
spin = "*"
rand = "*"

[dependencies.linked-hash-map]
git="https://github.com/contain-rs/linked-hash-map.git"

[dependencies.tendril]
git="https://github.com/arthurprs/tendril.git"
commit="d8c86398743c7e885fa6dcc1af9485bdf79b5a51"

[profile.dev]
opt-level = 0
debug = true
rpath = false
lto = false
debug-assertions = true
codegen-units = 8

[profile.release]
opt-level = 3
debug = false
rpath = false
lto = false
debug-assertions = false
codegen-units = 1
