[package]
name = "floki"
version = "0.1.0"
authors = ["arthurprs <arthurprs@gmail.com>"]

[dependencies]
rustc-serialize = "*"
log = "*"
env_logger = "*"
mio = "0.4.*"
nix = "0.3.6"
toml = "*"
threadpool = "*"
clock_ticks = "*"
num_cpus = "*"
fnv = "*"
spin = "*"

[dependencies.linked-hash-map]
git="https://github.com/arthurprs/linked-hash-map.git"

[dependencies.vec_map]
version="*"
features=["nightly"]


[profile.dev]
opt-level = 0
debug = true
rpath = false
lto = false
debug-assertions = true
codegen-units = 8

[profile.release]
opt-level = 3
debug = false
rpath = false
lto = false
debug-assertions = false
codegen-units = 1
