bind_address="127.0.0.1:9797"
data_directory="./data/"
segment_size="128mb"
maintenance_interval="1s"
max_connections=1024
message_timeout="30s"
retention_period="0d"
hard_retention_period="1d"
retention_size="0b"
hard_retention_size="1gb"
